name: Reusable Kubernetes Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      MONGO_USERNAME:
        required: true
        type: string
    secrets:
      KUBECONFIG:
        required: true
      MONGO_PASSWORD:
        required: true

jobs:
  deploy:
    runs-on: dev
    environment: ${{ inputs.environment }}
    outputs:
      endpoint: ${{ steps.set-output.outputs.endpoint }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # - name: Set up kubeconfig
      #   run: |
      #     mkdir -p ~/.kube
      #     echo "secrets.KUBECONFIG" > ~/.kube/config

      - name: Template manifests
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKER_USERNAME }}/solar-system:${{ inputs.image_tag }}
        run: |
          for f in kubernetes/${{ inputs.environment }}/*.yaml; do
            envsubst < "$f" > "rendered-$(basename $f)"
          done

      - name: Create namespace if not exists
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
        run: |
          kubectl get namespace "$NAMESPACE" || kubectl create namespace "$NAMESPACE"

      - name: Deploy to Kubernetes
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
        run: |
          kubectl apply -f rendered-deployment.yaml -n "$NAMESPACE"
          kubectl apply -f rendered-service.yaml -n "$NAMESPACE"
          kubectl apply -f rendered-ingress.yaml -n "$NAMESPACE"

      - name: Get Service Endpoint
        id: set-output
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
        run: |
          ENDPOINT=$(kubectl get svc solar-system -n "$NAMESPACE" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "endpoint=$ENDPOINT" >> $GITHUB_OUTPUT

